# How I think config should look like
meta:
  version: v2
  relabeling:
    projects:
      1111111: service-one
      1111112: service-two
    groups:
      1111111: group-one
config:
  teams:
    name: default
    projects: []
    groups: []
  users:
    - user:
        id: user_id
        name: name
        username: username
        email: email
      projects:
        - service-one: Developer
        - 111113: Guest
      groups:
        - group-one: Guest
        - 111112: Maintainer
      teams:
        - team_1
        - team_2
        - team_3
state:
  data: ~
