teams:
- name: default
  projects: []
- name: itigris
  projects:
  - name: common-wiki
    id: 19030434
    access_level: DEVELOPER
  - name: apply-sql
    id: 30222667
    access_level: REPORTER
  - name: gitlab-templates
    id: 27623091
    access_level: DEVELOPER
  - name: doc-ops
    id: 19675228
    access_level: DEVELOPER
- name: frontend-team
  projects:
  - name: frontend-static
    id: 28489285
    access_level: DEVELOPER
  - name: frontend-kit
    id: 20596509
    access_level: DEVELOPER
  - name: registry-npm
    id: 20591047
    access_level: DEVELOPER
- name: backend-team
  projects:
  - name: hr-backend
    id: 27834405
    access_level: REPORTER
  - name: optima-2-backend
    id: 23111998
    access_level: REPORTER
  - name: alcon-backend
    id: 21869854
    access_level: REPORTER
  - name: optimarket-backend
    id: 20464065
    access_level: REPORTER
  - name: coopervision-backend
    id: 20978763
    access_level: REPORTER
  - name: optima-admin-2-backend
    id: 20073121
    access_level: REPORTER
  - name: web-ordering-backend
    id: 19569718
    access_level: REPORTER
  - name: optidata-backend
    id: 18635831
    access_level: REPORTER
  - name: bi-service-backend
    id: 18460190
    access_level: REPORTER
  - name: optima-backend
    id: 18192112
    access_level: REPORTER
users:
- id: 9394865
  name: i.popugaev
  teams:
  - itigris
  - backend-team
  projects:
  - name: optima-backend
    id: 18192112
    access_level: DEVELOPER
  - name: optima-2-backend
    id: 23111998
    access_level: DEVELOPER
  - name: optima-admin-2-tests
    id: 31826862
    access_level: DEVELOPER
  - name: optima-tests
    id: 19143906
    access_level: DEVELOPER
  - name: optima-notification
    id: 21361740
    access_level: DEVELOPER
  - name: optima-docker-compose
    id: 28408952
    access_level: REPORTER
  - name: optima-admin-2-backend
    id: 20073121
    access_level: DEVELOPER
  - name: optima-frontend
    id: 19143891
    access_level: DEVELOPER
  ownerships: []
- id: 6012633
  name: n.rodionov
  teams: []
  projects: []
  ownerships:
  - name: itigris
    id: 7620949
    url: https://gitlab.com/groups/itigris
